name: swords_and_magic
description: A sample command-line application.
version: 0.0.8+8
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
